index:
  path: /
  controller: App\Controller\MainController::index

profile:
  path: /profile
  controller: App\Controller\MainController::profile

admin:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index
