index:
  path: /
  controller: App\Controller\MainController::index

profile:
  path: /profile
  controller: App\Controller\MainController::profile

admin:
  path: /admin
  controller: App\Controller\AdminController::index

addbook:
  path: /admin/addbook
  controller: App\Controller\AdminController::addbook

booklist:
  path: /admin/booklist
  controller: App\Controller\AdminController::booklist

updatebook:
  path: /admin/updatebook/{id}
  controller: App\Controller\AdminController::updatebook

deletebook:
  path: /admin/deletebook/{id}
  controller: App\Controller\AdminController::deletebook

